name = 'iskcon-elites-network'
main = ".open-next/worker.js"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat", "global_fetch_strictly_public"]

[assets]
directory = ".open-next/assets"
binding = "ASSETS"

[[services]]
binding = "WORKER_SELF_REFERENCE"
service = "iskcon-elites-network"
[observability]
enabled = true

[[hyperdrive]]
binding = "HYPERDRIVE"
id = "04e1ff894ffd42188624efb652c18659"
localConnectionString = "postgresql://postgres.czgybxyroxlqqhyxrqhe:Y4T%25XjQt%40p!h.ds@aws-0-ap-south-1.pooler.supabase.com:5432/postgres"
